//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftPortScanner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftPortScanner.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Discovery port:  的本地化字符串。
        /// </summary>
        internal static string DiscoveryPort {
            get {
                return ResourceManager.GetString("DiscoveryPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 end port 的本地化字符串。
        /// </summary>
        internal static string EndPort {
            get {
                return ResourceManager.GetString("EndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fast scan 的本地化字符串。
        /// </summary>
        internal static string FastScan {
            get {
                return ResourceManager.GetString("FastScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempt to retrieve timeout through ICMP. 的本地化字符串。
        /// </summary>
        internal static string ICMP {
            get {
                return ResourceManager.GetString("ICMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 input unavailable 的本地化字符串。
        /// </summary>
        internal static string InputUnavailable {
            get {
                return ResourceManager.GetString("InputUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 server ip 的本地化字符串。
        /// </summary>
        internal static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scan interval 的本地化字符串。
        /// </summary>
        internal static string ScanInterval {
            get {
                return ResourceManager.GetString("ScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 start port 的本地化字符串。
        /// </summary>
        internal static string StartPort {
            get {
                return ResourceManager.GetString("StartPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start port scanning... 的本地化字符串。
        /// </summary>
        internal static string StartPortScanning {
            get {
                return ResourceManager.GetString("StartPortScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tcp connect timeout 的本地化字符串。
        /// </summary>
        internal static string TcpConnectTimeout {
            get {
                return ResourceManager.GetString("TcpConnectTimeout", resourceCulture);
            }
        }
    }
}
